const express = require('express');
const swaggerUi = require('swagger-ui-express');
const spec = require('./swagger');
const app = express();
app.use(require('helmet')());
app.use(require('cors')({ origin: process.env.ALLOWED_ORIGINS ? process.env.ALLOWED_ORIGINS.split(',') : false }));
app.use(require('morgan')('dev'));
app.use(require('compression')());
app.use(express.json({ limit: '100kb' }));
app.get('/health', (req, res) => res.json({ success: true, service: 'product-service' }));
app.get(['/openapi.json', '/api-docs.json'], (req, res) => res.json(spec));
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(spec));
app.use('/api/products', require('./routes/productRoutes'));
app.get('/api/categories', require('./middleware/asyncHandler')(require('./controllers/productController').getCategories));
app.use((req, res) => res.status(404).json({ success: false, message: 'Route không tồn tại' }));
app.use(require('./middleware/errorHandler'));
module.exports = app;
